### ISSUE TITLE
Add padding in all pages around title, padding blue, different size in homepage.  

### ISSUE THREAD

**Issue by jaripacheco** [jaripacheco/jaripacheco.github.io#3]
@tommymetz Want to have padding in all pages, with the title still linked, the padding the same color as the other box in the text, padding to be big on the photos page and small on the homepage.

**Comment by tommymetz** [comment]
Remember when we did this:
```
<div id="main_content" class="white_text">
        <div id="main_content_inside">

        </div>
</div>
```

The "main_content" has some css (look for #main_content in the css file) that gives it a blue background and some padding. Go find that css. Then "main_content_inside" (look for #main_content_inside in the css file) makes the inner part 400px and centered. So whatever you put inside there will be centered in a big blue padded box.

So try wrapping the title with those divs and it should put the blue padded box around the title.

**Comment by jaripacheco** [comment]
@tommymetz Hi tom, I don't know what I'm doing, it did put the blue box around the title but what happened is that the blue box also padded around the homepage and I don't know why. Also, I wanted to separate the navigation bar from the padded box of the title. I put 3 <br>s but the padded box also got bigger. I don't know what to do.

**Comment by jaripacheco** [comment]
I put 3 br

**Comment by tommymetz** [comment]
@jaripacheco are you trying to make it look like this?
<img width="1037" alt="Screen Shot 2020-06-25 at 6 55 56 AM" src="https://user-images.githubusercontent.com/6005734/85723939-f6d6e800-b6b0-11ea-8cf0-f678ba867aa3.png">

If so, have a look at the CSS in the bottom right corner of the image:

```
background-color: #012a79;
padding: 20px;
margin-bottom: 20px;
```

You can add that css to the link. Try adding it to the `yellow_text` class in your css like this:

```
.yellow_text {
    color: yellow;
    font-size: 50px;
    text-decoration: none;
    text-align: center;
    display: block;
    background-color: #012a79;
    padding: 20px;
    margin-bottom: 20px;
}
```

**Comment by jaripacheco** [comment]
@tommymetz thank you

**Comment by tommymetz** [comment]
@jaripacheco nice work!
