### ISSUE TITLE
Navigation bar not active

### ISSUE THREAD

**Issue by jaripacheco** [jaripacheco/jaripacheco.github.io#5]
@tommymetz Even though in the html and css it says for the page to be active where the person is, I don't know why it is not active. I think there is something wrong with the css.

**Comment by tommymetz** [comment]
@jaripacheco if you look at navigation bar code, you'll see `class="active"` on the Home link. For the photos and contact pages you can move it to those links instead of the home link and it will make those tabs active. Give that a try.

**Comment by jaripacheco** [comment]
@tommymetz Ok, thank you

**Comment by jaripacheco** [comment]
@tommymetz Hi Tom, sorry to bother you. I don't get what you're saying.

**Comment by jaripacheco** [comment]
@tommymetz Thank you, I fixed it.

**Comment by tommymetz** [comment]
Awesome your getting the hang of it! Keep going!!!
